# Copyright 2022 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Author: Tim Fischer <fischeti@iis.ee.ethz.ch>

variables:
  UV_LINK_MODE: copy

before_script:
  - set -a && source .iis_env && set +a
  - /usr/local/uv/uv tool install rust-just --quiet
  - export PATH="${HOME}/.local/bin:${PATH}"

stages:
  - build
  - test

build-vsim:
  stage: build
  script:
    - just gen-regs ${NUM_CHANNELS}
    - WORK=work_${NUM_CHANNELS} just compile vsim
  parallel:
    matrix:
      - NUM_CHANNELS: [1, 4]
  artifacts:
    paths:
      - work_${NUM_CHANNELS}

build-vcs:
  stage: build
  script:
    - just gen-regs ${NUM_CHANNELS}
    - WORK=work_${NUM_CHANNELS} just compile vcs ${TB_DUT}
  parallel:
    matrix:
      - NUM_CHANNELS: [1, 4]
        TB_DUT: [tb_axi_slink, tb_ch_calib_slink]
  artifacts:
    paths:
      - work_${NUM_CHANNELS}/bin/${TB_DUT}.vcs*

run-vsim:
  stage: test
  needs:
    - build-vsim
  script:
    - echo "Running AXI test with R/W [$NUM_READS_1,$NUM_WRITES_1] <-> [$NUM_READS_2,$NUM_WRITES_2]"
    - >
      WORK=work_${NUM_CHANNELS} just run-batch vsim ${TB_DUT}
      "+NUM_READS_1=$NUM_READS_1 +NUM_WRITES_1=$NUM_WRITES_1
      +NUM_READS_2=$NUM_READS_2 +NUM_WRITES_2=$NUM_WRITES_2
      +NUM_FAULTS_1=$NUM_FAULTS_1 +NUM_FAULTS_2=$NUM_FAULTS_2"
      | tee vsim.log
    - '! grep -n "Error:" vsim.log'
    - '! grep -n "Fatal:" vsim.log'
  parallel:
    matrix:
      - TB_DUT: [tb_axi_slink]
        NUM_CHANNELS: [1, 4]
        NUM_READS_1: [0, 100]
        NUM_WRITES_1: [0, 100]
        NUM_READS_2: [0, 100]
        NUM_WRITES_2: [0, 100]
      - TB_DUT: [tb_ch_calib_slink]
        NUM_CHANNELS: [4]
        NUM_FAULTS_1: [0, 1, 2]
        NUM_FAULTS_2: [0, 1, 2]
        NUM_READS_1: [10]
        NUM_WRITES_1: [10]
        NUM_READS_2: [10]
        NUM_WRITES_2: [10]
  timeout: 15 minutes

run-vcs:
  stage: test
  needs:
    - build-vcs
  script:
    - echo "Running AXI test with R/W [$NUM_READS_1,$NUM_WRITES_1] <-> [$NUM_READS_2,$NUM_WRITES_2]"
    - >
      WORK=work_${NUM_CHANNELS} just run-batch vcs ${TB_DUT}
      "+NUM_READS_1=$NUM_READS_1 +NUM_WRITES_1=$NUM_WRITES_1
      +NUM_READS_2=$NUM_READS_2 +NUM_WRITES_2=$NUM_WRITES_2
      +NUM_FAULTS_1=$NUM_FAULTS_1 +NUM_FAULTS_2=$NUM_FAULTS_2"
      | tee vcs.log
    - '! grep -n "Error-\[" vcs.log'
  parallel:
    matrix:
      - TB_DUT: [tb_axi_slink]
        NUM_CHANNELS: [1, 4]
        NUM_READS_1: [0, 100]
        NUM_WRITES_1: [0, 100]
        NUM_READS_2: [0, 100]
        NUM_WRITES_2: [0, 100]
      - TB_DUT: [tb_ch_calib_slink]
        NUM_CHANNELS: [4]
        NUM_FAULTS_1: [0, 1, 2]
        NUM_FAULTS_2: [0, 1, 2]
        NUM_READS_1: [10]
        NUM_WRITES_1: [10]
        NUM_READS_2: [10]
        NUM_WRITES_2: [10]
  timeout: 15 minutes
