onerror {resume}
quietly virtual function -install /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network -env /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network { &{/tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.rob_req, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.rob_idx, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.src_id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.last, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.axi_ch, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.rsvd }} narrow_req_i_data_gen
quietly virtual function -install /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network -env /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network { &{/tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_i.data.gen.rob_req, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_i.data.gen.rob_idx, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_i.data.gen.id, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_i.data.gen.src_id, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_i.data.gen.last, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_i.data.gen.axi_ch, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_i.data.gen.rsvd }} narrow_req_i_data_gen
quietly virtual function -install /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network -env /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network { &{/tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.rob_req, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.rob_idx, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.src_id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.last, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.axi_ch, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.rsvd }} data001
quietly virtual function -install /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network -env /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network { &{/tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.rob_req, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.rob_idx, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.src_id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.last, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.axi_ch, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data.gen.rsvd }} data_req_flit_in
quietly virtual function -install /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network -env /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network { &{/tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.data.gen.rob_req, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.data.gen.rob_idx, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.data.gen.id, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.data.gen.src_id, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.data.gen.last, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.data.gen.axi_ch, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.data.gen.rsvd }} narrow_req_o_data_gen
quietly virtual function -install /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network -env /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network { &{/tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.rob_req, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.rob_idx, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.src_id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.last, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.axi_ch, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.rsvd }} narrow_rsp_i_data_gen
quietly virtual function -install /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network -env /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network { &{/tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.data.gen.rob_req, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.data.gen.rob_idx, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.data.gen.id, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.data.gen.src_id, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.data.gen.last, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.data.gen.axi_ch, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.data.gen.rsvd }} narrow_rsp_o_data_gen
quietly virtual function -install /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network -env /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network { &{/tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_o.data.gen.rob_req, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_o.data.gen.rob_idx, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_o.data.gen.id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_o.data.gen.src_id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_o.data.gen.last, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_o.data.gen.axi_ch, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_o.data.gen.rsvd }} narrow_req_o_data_gen
quietly virtual function -install /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network -env /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network { &{/tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_i.data.gen.rob_req, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_i.data.gen.rob_idx, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_i.data.gen.id, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_i.data.gen.src_id, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_i.data.gen.last, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_i.data.gen.axi_ch, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_i.data.gen.rsvd }} narrow_rsp_i_data_gen
quietly virtual function -install /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network -env /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network { &{/tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_o.data.gen.rob_req, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_o.data.gen.rob_idx, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_o.data.gen.id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_o.data.gen.src_id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_o.data.gen.last, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_o.data.gen.axi_ch, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_o.data.gen.rsvd }} narrow_rsp_o_data_gen
quietly virtual function -install /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network -env /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network { &{/tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.rob_req, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.rob_idx, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.src_id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.last, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.axi_ch, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.rsvd }} data
quietly virtual function -install /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network -env /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network { &{/tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.rob_req, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.rob_idx, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.src_id, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.last, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.axi_ch, /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data.gen.rsvd }} data_rsp_flit_in
quietly virtual function -install /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network -env /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network { &{/tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.data.gen.rob_req, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.data.gen.rob_idx, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.data.gen.id, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.data.gen.src_id, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.data.gen.last, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.data.gen.axi_ch, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.data.gen.rsvd }} data_req_flit_out
quietly virtual function -install /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network -env /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network { &{/tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.data.gen.rob_req, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.data.gen.rob_idx, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.data.gen.id, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.data.gen.src_id, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.data.gen.last, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.data.gen.axi_ch, /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.data.gen.rsvd }} data_rsp_flit_out
quietly WaveActivateNextPane {} 0
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -color Yellow /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/clk_i
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group flit_in -group req_flit_in -label valid -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.valid
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group flit_in -group req_flit_in -label ready -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_o.ready
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group flit_in -group req_flit_in -color Cyan -label data /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/data_req_flit_in
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group flit_in -group req_flit_in -color Aquamarine -label data_axi_style /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_req_i.data
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group flit_in -group rsp_flit_in -label valid -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.valid
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group flit_in -group rsp_flit_in -label ready -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_o.ready
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group flit_in -group rsp_flit_in -color Cyan -label data /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/data_rsp_flit_in
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group flit_in -group rsp_flit_in -color Aquamarine -label data_axi_style /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/narrow_rsp_i.data
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group synchronization_credits_out -group req_synchronization_out /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/i_credit_counter_req/*
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group synchronization_credits_out -group rsp_synchronization_out /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/i_credit_counter_rsp/*
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group synchronization_credits_out -group wide_synchronization_out /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/i_credit_counter_wide/*
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_in -group req_arbiter_in -color Orange -label data_hdr /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_arbiter_in.data_hdr
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_in -group req_arbiter_in -label { valid} -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_valid_synchr_out
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_in -group req_arbiter_in -label ready -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_ready_synchr_out
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_in -group req_arbiter_in -color Cyan -label data /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_arbiter_in.data
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_in -group req_arbiter_in -color Red -label data_validity /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_arbiter_in.data_validity
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_in -group req_arbiter_in -color Orange -label credits_hdr /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_arbiter_in.credits_hdr
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_in -group req_arbiter_in -color Violet -label credits -radix unsigned /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_arbiter_in.credits
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_in -group rsp_arbiter_in -color Orange -label data_hdr /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/rsp_arbiter_in.data_hdr
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_in -group rsp_arbiter_in -label valid -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/rsp_valid_synchr_out
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_in -group rsp_arbiter_in -label ready -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/rsp_ready_synchr_out
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_in -group rsp_arbiter_in -color Cyan -label data /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/rsp_arbiter_in.data
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_in -group rsp_arbiter_in -color Red -label data_validity /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/rsp_arbiter_in.data_validity
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_in -group rsp_arbiter_in -color Orange -label credits_hdr /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/rsp_arbiter_in.credits_hdr
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_in -group rsp_arbiter_in -color Violet -label credits -radix unsigned /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/rsp_arbiter_in.credits
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_out -color Orange -label data_hdr /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_rsp_arbiter_out.data_hdr
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_out -label valid -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/axis_out_valid
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_out -label ready -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/axis_out_ready
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_out -color Cyan -label data /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_rsp_arbiter_out.data
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_out -color Red -label data_validity /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_rsp_arbiter_out.data_validity
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_out -color Orange -label credits_hdr /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_rsp_arbiter_out.credits_hdr
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group arbiter_out -color Violet -label credits -radix unsigned /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_rsp_arbiter_out.credits
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group axis_out -color Orange -label data_hdr /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_rsp_axis_out.data_hdr
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group axis_out -label valid -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/axis_out_req_o.tvalid
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group axis_out -label ready -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/axis_out_rsp_i.tready
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group axis_out -color Cyan -label data /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_rsp_axis_out.data
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group axis_out -color Red -label data_validity /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_rsp_axis_out.data_validity
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group axis_out -color Orange -label credits_hdr /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_rsp_axis_out.credits_hdr
add wave -noupdate -group full_data_path_debugging -group flit_to_axis_bridge_0 -group axis_out -color Violet -label credits -radix unsigned /tb_floo_serial_link_narrow_wide/i_serial_link_0/bridge/i_serial_link_network/req_rsp_axis_out.credits
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -color Yellow /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/clk_i
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group axis_in -color Orange -label data_hdr /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/req_rsp_queue_in.data_hdr
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group axis_in -label valid -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/axis_in_req_i.tvalid
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group axis_in -label ready -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/axis_in_rsp_o.tready
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group axis_in -color Cyan -label data /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/req_rsp_queue_in.data
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group axis_in -color Red -label data_validity /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/req_rsp_queue_in.data_validity
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group axis_in -color Orange -label credits_hdr /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/req_rsp_queue_in.credits_hdr
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group axis_in -color Violet -label credits -radix unsigned /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/req_rsp_queue_in.credits
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_in -group req_queue_in -color Orange -label data_hdr /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/req_rsp_queue_in.data_hdr
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_in -group req_queue_in -label valid -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/axis_data_in_req_valid
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_in -group req_queue_in -label ready -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/axis_data_in_req_ready
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_in -group req_queue_in -color Cyan -label data /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/req_rsp_queue_in.data
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_in -group req_queue_in -color Red -label data_validity /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/req_rsp_queue_in.data_validity
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_in -group req_queue_in -color Orange -label credits_hdr /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/req_rsp_queue_in.credits_hdr
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_in -group req_queue_in -color Violet -label credits -radix unsigned /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/req_rsp_queue_in.credits
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_in -group rsp_queue_in -color Orange -label data_hdr /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/req_rsp_queue_in.data_hdr
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_in -group rsp_queue_in -label valid -radix unsigned /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/axis_data_in_rsp_valid
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_in -group rsp_queue_in -label ready -radix unsigned /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/axis_data_in_rsp_ready
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_in -group rsp_queue_in -color Cyan -label data /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/req_rsp_queue_in.data
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_in -group rsp_queue_in -color Red -label data_validity /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/req_rsp_queue_in.data_validity
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_in -group rsp_queue_in -color Orange -label credits_hdr /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/req_rsp_queue_in.credits_hdr
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_in -group rsp_queue_in -color Violet -label credits -radix unsigned /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/req_rsp_queue_in.credits
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_out -group req_queue_out /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/i_axis_in_req_reg/valid_o
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_out -group req_queue_out /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/i_axis_in_req_reg/ready_i
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_out -group req_queue_out -color Cyan /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/i_axis_in_req_reg/data_o
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_out -group rsp_queue_out /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/i_axis_in_rsp_reg/valid_o
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_out -group rsp_queue_out /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/i_axis_in_rsp_reg/ready_i
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group queue_out -group rsp_queue_out -color Cyan /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/i_axis_in_rsp_reg/data_o
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group synchronization_credits_in -group req_synchronization_in /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/i_credit_counter_req/*
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group synchronization_credits_in -group rsp_synchronization_in /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/i_credit_counter_rsp/*
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group synchronization_credits_in -group wide_synchronization_in /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/i_credit_counter_wide/*
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group flit_out -group req_flit_out -label valid -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.valid
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group flit_out -group req_flit_out -label ready -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_i.ready
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group flit_out -group req_flit_out -color Cyan -label data /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/data_req_flit_out
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group flit_out -group req_flit_out -color Aquamarine -label data_axi_style /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_req_o.data
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group flit_out -group rsp_flit_out -label valid -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.valid
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group flit_out -group rsp_flit_out -label ready -radix ufixed -radixshowbase 1 /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_i.ready
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group flit_out -group rsp_flit_out -color Cyan -label data /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/data_rsp_flit_out
add wave -noupdate -group full_data_path_debugging -group axis_to_flit_bridge_1 -group flit_out -group rsp_flit_out -color Aquamarine -label data_axi_style /tb_floo_serial_link_narrow_wide/i_serial_link_1/bridge/i_serial_link_network/narrow_rsp_o.data
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 220
configure wave -valuecolwidth 110
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {723680 ps}
