// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package serial_link_reg_pkg;

  // Param list
  parameter int NumChannels = 20;
  parameter int Log2NumChannels = 5;
  parameter int NumBits = 16;
  parameter int Log2MaxClkDiv = 10;
  parameter int FlushCounterWidth = 8;
  parameter int Log2RawModeTXFifoDepth = 3;

  // Address widths within the block
  parameter int BlockAw = 8;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } clk_ena;
    struct packed {
      logic        q;
    } reset_n;
    struct packed {
      logic        q;
    } axi_in_isolate;
    struct packed {
      logic        q;
    } axi_out_isolate;
  } serial_link_reg2hw_ctrl_reg_t;

  typedef struct packed {
    logic [10:0] q;
  } serial_link_reg2hw_tx_phy_ctrl1_mreg_t;

  typedef struct packed {
    struct packed {
      logic [10:0] q;
    } clk_shift_start;
    struct packed {
      logic [10:0] q;
    } clk_shift_end;
  } serial_link_reg2hw_tx_phy_ctrl2_mreg_t;

  typedef struct packed {
    logic        q;
  } serial_link_reg2hw_raw_mode_en_reg_t;

  typedef struct packed {
    logic [4:0]  q;
  } serial_link_reg2hw_raw_mode_in_ch_sel_reg_t;

  typedef struct packed {
    logic [15:0] q;
    logic        re;
  } serial_link_reg2hw_raw_mode_in_data_reg_t;

  typedef struct packed {
    logic        q;
  } serial_link_reg2hw_raw_mode_out_ch_mask_mreg_t;

  typedef struct packed {
    logic [15:0] q;
    logic        qe;
  } serial_link_reg2hw_raw_mode_out_data_fifo_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } clear;
  } serial_link_reg2hw_raw_mode_out_data_fifo_ctrl_reg_t;

  typedef struct packed {
    logic        q;
  } serial_link_reg2hw_raw_mode_out_en_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } serial_link_reg2hw_flow_control_fifo_clear_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } bypass_en;
    struct packed {
      logic        q;
    } auto_flush_en;
    struct packed {
      logic [7:0]  q;
    } auto_flush_count;
  } serial_link_reg2hw_channel_alloc_tx_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } serial_link_reg2hw_channel_alloc_tx_ch_en_mreg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } clear;
    struct packed {
      logic        q;
      logic        qe;
    } flush;
  } serial_link_reg2hw_channel_alloc_tx_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } bypass_en;
    struct packed {
      logic        q;
    } auto_flush_en;
    struct packed {
      logic [7:0]  q;
    } auto_flush_count;
    struct packed {
      logic        q;
    } sync_en;
  } serial_link_reg2hw_channel_alloc_rx_cfg_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } serial_link_reg2hw_channel_alloc_rx_ctrl_reg_t;

  typedef struct packed {
    logic        q;
  } serial_link_reg2hw_channel_alloc_rx_ch_en_mreg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } axi_in;
    struct packed {
      logic        d;
    } axi_out;
  } serial_link_hw2reg_isolated_reg_t;

  typedef struct packed {
    logic        d;
  } serial_link_hw2reg_raw_mode_in_data_valid_mreg_t;

  typedef struct packed {
    logic [15:0] d;
  } serial_link_hw2reg_raw_mode_in_data_reg_t;

  typedef struct packed {
    struct packed {
      logic [2:0]  d;
    } fill_state;
    struct packed {
      logic        d;
    } is_full;
  } serial_link_hw2reg_raw_mode_out_data_fifo_ctrl_reg_t;

  // Register -> HW type
  typedef struct packed {
    serial_link_reg2hw_ctrl_reg_t ctrl; // [795:792]
    serial_link_reg2hw_tx_phy_ctrl1_mreg_t [19:0] tx_phy_ctrl1; // [791:572]
    serial_link_reg2hw_tx_phy_ctrl2_mreg_t [19:0] tx_phy_ctrl2; // [571:132]
    serial_link_reg2hw_raw_mode_en_reg_t raw_mode_en; // [131:131]
    serial_link_reg2hw_raw_mode_in_ch_sel_reg_t raw_mode_in_ch_sel; // [130:126]
    serial_link_reg2hw_raw_mode_in_data_reg_t raw_mode_in_data; // [125:109]
    serial_link_reg2hw_raw_mode_out_ch_mask_mreg_t [19:0] raw_mode_out_ch_mask; // [108:89]
    serial_link_reg2hw_raw_mode_out_data_fifo_reg_t raw_mode_out_data_fifo; // [88:72]
    serial_link_reg2hw_raw_mode_out_data_fifo_ctrl_reg_t raw_mode_out_data_fifo_ctrl; // [71:70]
    serial_link_reg2hw_raw_mode_out_en_reg_t raw_mode_out_en; // [69:69]
    serial_link_reg2hw_flow_control_fifo_clear_reg_t flow_control_fifo_clear; // [68:67]
    serial_link_reg2hw_channel_alloc_tx_cfg_reg_t channel_alloc_tx_cfg; // [66:57]
    serial_link_reg2hw_channel_alloc_tx_ch_en_mreg_t [19:0] channel_alloc_tx_ch_en; // [56:37]
    serial_link_reg2hw_channel_alloc_tx_ctrl_reg_t channel_alloc_tx_ctrl; // [36:33]
    serial_link_reg2hw_channel_alloc_rx_cfg_reg_t channel_alloc_rx_cfg; // [32:22]
    serial_link_reg2hw_channel_alloc_rx_ctrl_reg_t channel_alloc_rx_ctrl; // [21:20]
    serial_link_reg2hw_channel_alloc_rx_ch_en_mreg_t [19:0] channel_alloc_rx_ch_en; // [19:0]
  } serial_link_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    serial_link_hw2reg_isolated_reg_t isolated; // [41:40]
    serial_link_hw2reg_raw_mode_in_data_valid_mreg_t [19:0] raw_mode_in_data_valid; // [39:20]
    serial_link_hw2reg_raw_mode_in_data_reg_t raw_mode_in_data; // [19:4]
    serial_link_hw2reg_raw_mode_out_data_fifo_ctrl_reg_t raw_mode_out_data_fifo_ctrl; // [3:0]
  } serial_link_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] SERIAL_LINK_CTRL_OFFSET = 8'h 0;
  parameter logic [BlockAw-1:0] SERIAL_LINK_ISOLATED_OFFSET = 8'h 4;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_0_OFFSET = 8'h 8;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_1_OFFSET = 8'h c;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_2_OFFSET = 8'h 10;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_3_OFFSET = 8'h 14;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_4_OFFSET = 8'h 18;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_5_OFFSET = 8'h 1c;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_6_OFFSET = 8'h 20;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_7_OFFSET = 8'h 24;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_8_OFFSET = 8'h 28;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_9_OFFSET = 8'h 2c;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_10_OFFSET = 8'h 30;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_11_OFFSET = 8'h 34;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_12_OFFSET = 8'h 38;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_13_OFFSET = 8'h 3c;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_14_OFFSET = 8'h 40;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_15_OFFSET = 8'h 44;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_16_OFFSET = 8'h 48;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_17_OFFSET = 8'h 4c;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_18_OFFSET = 8'h 50;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL1_19_OFFSET = 8'h 54;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_0_OFFSET = 8'h 58;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_1_OFFSET = 8'h 5c;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_2_OFFSET = 8'h 60;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_3_OFFSET = 8'h 64;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_4_OFFSET = 8'h 68;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_5_OFFSET = 8'h 6c;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_6_OFFSET = 8'h 70;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_7_OFFSET = 8'h 74;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_8_OFFSET = 8'h 78;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_9_OFFSET = 8'h 7c;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_10_OFFSET = 8'h 80;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_11_OFFSET = 8'h 84;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_12_OFFSET = 8'h 88;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_13_OFFSET = 8'h 8c;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_14_OFFSET = 8'h 90;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_15_OFFSET = 8'h 94;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_16_OFFSET = 8'h 98;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_17_OFFSET = 8'h 9c;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_18_OFFSET = 8'h a0;
  parameter logic [BlockAw-1:0] SERIAL_LINK_TX_PHY_CTRL2_19_OFFSET = 8'h a4;
  parameter logic [BlockAw-1:0] SERIAL_LINK_RAW_MODE_EN_OFFSET = 8'h a8;
  parameter logic [BlockAw-1:0] SERIAL_LINK_RAW_MODE_IN_CH_SEL_OFFSET = 8'h ac;
  parameter logic [BlockAw-1:0] SERIAL_LINK_RAW_MODE_IN_DATA_VALID_OFFSET = 8'h b0;
  parameter logic [BlockAw-1:0] SERIAL_LINK_RAW_MODE_IN_DATA_OFFSET = 8'h b4;
  parameter logic [BlockAw-1:0] SERIAL_LINK_RAW_MODE_OUT_CH_MASK_OFFSET = 8'h b8;
  parameter logic [BlockAw-1:0] SERIAL_LINK_RAW_MODE_OUT_DATA_FIFO_OFFSET = 8'h bc;
  parameter logic [BlockAw-1:0] SERIAL_LINK_RAW_MODE_OUT_DATA_FIFO_CTRL_OFFSET = 8'h c0;
  parameter logic [BlockAw-1:0] SERIAL_LINK_RAW_MODE_OUT_EN_OFFSET = 8'h c4;
  parameter logic [BlockAw-1:0] SERIAL_LINK_FLOW_CONTROL_FIFO_CLEAR_OFFSET = 8'h c8;
  parameter logic [BlockAw-1:0] SERIAL_LINK_CHANNEL_ALLOC_TX_CFG_OFFSET = 8'h cc;
  parameter logic [BlockAw-1:0] SERIAL_LINK_CHANNEL_ALLOC_TX_CH_EN_OFFSET = 8'h d0;
  parameter logic [BlockAw-1:0] SERIAL_LINK_CHANNEL_ALLOC_TX_CTRL_OFFSET = 8'h d4;
  parameter logic [BlockAw-1:0] SERIAL_LINK_CHANNEL_ALLOC_RX_CFG_OFFSET = 8'h d8;
  parameter logic [BlockAw-1:0] SERIAL_LINK_CHANNEL_ALLOC_RX_CTRL_OFFSET = 8'h dc;
  parameter logic [BlockAw-1:0] SERIAL_LINK_CHANNEL_ALLOC_RX_CH_EN_OFFSET = 8'h e0;

  // Reset values for hwext registers and their fields
  parameter logic [1:0] SERIAL_LINK_ISOLATED_RESVAL = 2'h 3;
  parameter logic [0:0] SERIAL_LINK_ISOLATED_AXI_IN_RESVAL = 1'h 1;
  parameter logic [0:0] SERIAL_LINK_ISOLATED_AXI_OUT_RESVAL = 1'h 1;
  parameter logic [19:0] SERIAL_LINK_RAW_MODE_IN_DATA_VALID_RESVAL = 20'h 0;
  parameter logic [15:0] SERIAL_LINK_RAW_MODE_IN_DATA_RESVAL = 16'h 0;
  parameter logic [31:0] SERIAL_LINK_RAW_MODE_OUT_DATA_FIFO_CTRL_RESVAL = 32'h 0;
  parameter logic [2:0] SERIAL_LINK_RAW_MODE_OUT_DATA_FIFO_CTRL_FILL_STATE_RESVAL = 3'h 0;
  parameter logic [0:0] SERIAL_LINK_RAW_MODE_OUT_DATA_FIFO_CTRL_IS_FULL_RESVAL = 1'h 0;
  parameter logic [0:0] SERIAL_LINK_FLOW_CONTROL_FIFO_CLEAR_RESVAL = 1'h 0;
  parameter logic [0:0] SERIAL_LINK_FLOW_CONTROL_FIFO_CLEAR_FLOW_CONTROL_FIFO_CLEAR_RESVAL = 1'h 0;
  parameter logic [1:0] SERIAL_LINK_CHANNEL_ALLOC_TX_CTRL_RESVAL = 2'h 0;
  parameter logic [0:0] SERIAL_LINK_CHANNEL_ALLOC_RX_CTRL_RESVAL = 1'h 0;

  // Register index
  typedef enum int {
    SERIAL_LINK_CTRL,
    SERIAL_LINK_ISOLATED,
    SERIAL_LINK_TX_PHY_CTRL1_0,
    SERIAL_LINK_TX_PHY_CTRL1_1,
    SERIAL_LINK_TX_PHY_CTRL1_2,
    SERIAL_LINK_TX_PHY_CTRL1_3,
    SERIAL_LINK_TX_PHY_CTRL1_4,
    SERIAL_LINK_TX_PHY_CTRL1_5,
    SERIAL_LINK_TX_PHY_CTRL1_6,
    SERIAL_LINK_TX_PHY_CTRL1_7,
    SERIAL_LINK_TX_PHY_CTRL1_8,
    SERIAL_LINK_TX_PHY_CTRL1_9,
    SERIAL_LINK_TX_PHY_CTRL1_10,
    SERIAL_LINK_TX_PHY_CTRL1_11,
    SERIAL_LINK_TX_PHY_CTRL1_12,
    SERIAL_LINK_TX_PHY_CTRL1_13,
    SERIAL_LINK_TX_PHY_CTRL1_14,
    SERIAL_LINK_TX_PHY_CTRL1_15,
    SERIAL_LINK_TX_PHY_CTRL1_16,
    SERIAL_LINK_TX_PHY_CTRL1_17,
    SERIAL_LINK_TX_PHY_CTRL1_18,
    SERIAL_LINK_TX_PHY_CTRL1_19,
    SERIAL_LINK_TX_PHY_CTRL2_0,
    SERIAL_LINK_TX_PHY_CTRL2_1,
    SERIAL_LINK_TX_PHY_CTRL2_2,
    SERIAL_LINK_TX_PHY_CTRL2_3,
    SERIAL_LINK_TX_PHY_CTRL2_4,
    SERIAL_LINK_TX_PHY_CTRL2_5,
    SERIAL_LINK_TX_PHY_CTRL2_6,
    SERIAL_LINK_TX_PHY_CTRL2_7,
    SERIAL_LINK_TX_PHY_CTRL2_8,
    SERIAL_LINK_TX_PHY_CTRL2_9,
    SERIAL_LINK_TX_PHY_CTRL2_10,
    SERIAL_LINK_TX_PHY_CTRL2_11,
    SERIAL_LINK_TX_PHY_CTRL2_12,
    SERIAL_LINK_TX_PHY_CTRL2_13,
    SERIAL_LINK_TX_PHY_CTRL2_14,
    SERIAL_LINK_TX_PHY_CTRL2_15,
    SERIAL_LINK_TX_PHY_CTRL2_16,
    SERIAL_LINK_TX_PHY_CTRL2_17,
    SERIAL_LINK_TX_PHY_CTRL2_18,
    SERIAL_LINK_TX_PHY_CTRL2_19,
    SERIAL_LINK_RAW_MODE_EN,
    SERIAL_LINK_RAW_MODE_IN_CH_SEL,
    SERIAL_LINK_RAW_MODE_IN_DATA_VALID,
    SERIAL_LINK_RAW_MODE_IN_DATA,
    SERIAL_LINK_RAW_MODE_OUT_CH_MASK,
    SERIAL_LINK_RAW_MODE_OUT_DATA_FIFO,
    SERIAL_LINK_RAW_MODE_OUT_DATA_FIFO_CTRL,
    SERIAL_LINK_RAW_MODE_OUT_EN,
    SERIAL_LINK_FLOW_CONTROL_FIFO_CLEAR,
    SERIAL_LINK_CHANNEL_ALLOC_TX_CFG,
    SERIAL_LINK_CHANNEL_ALLOC_TX_CH_EN,
    SERIAL_LINK_CHANNEL_ALLOC_TX_CTRL,
    SERIAL_LINK_CHANNEL_ALLOC_RX_CFG,
    SERIAL_LINK_CHANNEL_ALLOC_RX_CTRL,
    SERIAL_LINK_CHANNEL_ALLOC_RX_CH_EN
  } serial_link_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] SERIAL_LINK_PERMIT [57] = '{
    4'b 0011, // index[ 0] SERIAL_LINK_CTRL
    4'b 0001, // index[ 1] SERIAL_LINK_ISOLATED
    4'b 0011, // index[ 2] SERIAL_LINK_TX_PHY_CTRL1_0
    4'b 0011, // index[ 3] SERIAL_LINK_TX_PHY_CTRL1_1
    4'b 0011, // index[ 4] SERIAL_LINK_TX_PHY_CTRL1_2
    4'b 0011, // index[ 5] SERIAL_LINK_TX_PHY_CTRL1_3
    4'b 0011, // index[ 6] SERIAL_LINK_TX_PHY_CTRL1_4
    4'b 0011, // index[ 7] SERIAL_LINK_TX_PHY_CTRL1_5
    4'b 0011, // index[ 8] SERIAL_LINK_TX_PHY_CTRL1_6
    4'b 0011, // index[ 9] SERIAL_LINK_TX_PHY_CTRL1_7
    4'b 0011, // index[10] SERIAL_LINK_TX_PHY_CTRL1_8
    4'b 0011, // index[11] SERIAL_LINK_TX_PHY_CTRL1_9
    4'b 0011, // index[12] SERIAL_LINK_TX_PHY_CTRL1_10
    4'b 0011, // index[13] SERIAL_LINK_TX_PHY_CTRL1_11
    4'b 0011, // index[14] SERIAL_LINK_TX_PHY_CTRL1_12
    4'b 0011, // index[15] SERIAL_LINK_TX_PHY_CTRL1_13
    4'b 0011, // index[16] SERIAL_LINK_TX_PHY_CTRL1_14
    4'b 0011, // index[17] SERIAL_LINK_TX_PHY_CTRL1_15
    4'b 0011, // index[18] SERIAL_LINK_TX_PHY_CTRL1_16
    4'b 0011, // index[19] SERIAL_LINK_TX_PHY_CTRL1_17
    4'b 0011, // index[20] SERIAL_LINK_TX_PHY_CTRL1_18
    4'b 0011, // index[21] SERIAL_LINK_TX_PHY_CTRL1_19
    4'b 0011, // index[22] SERIAL_LINK_TX_PHY_CTRL2_0
    4'b 0011, // index[23] SERIAL_LINK_TX_PHY_CTRL2_1
    4'b 0011, // index[24] SERIAL_LINK_TX_PHY_CTRL2_2
    4'b 0011, // index[25] SERIAL_LINK_TX_PHY_CTRL2_3
    4'b 0011, // index[26] SERIAL_LINK_TX_PHY_CTRL2_4
    4'b 0011, // index[27] SERIAL_LINK_TX_PHY_CTRL2_5
    4'b 0011, // index[28] SERIAL_LINK_TX_PHY_CTRL2_6
    4'b 0011, // index[29] SERIAL_LINK_TX_PHY_CTRL2_7
    4'b 0011, // index[30] SERIAL_LINK_TX_PHY_CTRL2_8
    4'b 0011, // index[31] SERIAL_LINK_TX_PHY_CTRL2_9
    4'b 0011, // index[32] SERIAL_LINK_TX_PHY_CTRL2_10
    4'b 0011, // index[33] SERIAL_LINK_TX_PHY_CTRL2_11
    4'b 0011, // index[34] SERIAL_LINK_TX_PHY_CTRL2_12
    4'b 0011, // index[35] SERIAL_LINK_TX_PHY_CTRL2_13
    4'b 0011, // index[36] SERIAL_LINK_TX_PHY_CTRL2_14
    4'b 0011, // index[37] SERIAL_LINK_TX_PHY_CTRL2_15
    4'b 0011, // index[38] SERIAL_LINK_TX_PHY_CTRL2_16
    4'b 0011, // index[39] SERIAL_LINK_TX_PHY_CTRL2_17
    4'b 0011, // index[40] SERIAL_LINK_TX_PHY_CTRL2_18
    4'b 0011, // index[41] SERIAL_LINK_TX_PHY_CTRL2_19
    4'b 0001, // index[42] SERIAL_LINK_RAW_MODE_EN
    4'b 0001, // index[43] SERIAL_LINK_RAW_MODE_IN_CH_SEL
    4'b 0111, // index[44] SERIAL_LINK_RAW_MODE_IN_DATA_VALID
    4'b 0011, // index[45] SERIAL_LINK_RAW_MODE_IN_DATA
    4'b 0111, // index[46] SERIAL_LINK_RAW_MODE_OUT_CH_MASK
    4'b 0011, // index[47] SERIAL_LINK_RAW_MODE_OUT_DATA_FIFO
    4'b 1111, // index[48] SERIAL_LINK_RAW_MODE_OUT_DATA_FIFO_CTRL
    4'b 0001, // index[49] SERIAL_LINK_RAW_MODE_OUT_EN
    4'b 0001, // index[50] SERIAL_LINK_FLOW_CONTROL_FIFO_CLEAR
    4'b 0011, // index[51] SERIAL_LINK_CHANNEL_ALLOC_TX_CFG
    4'b 0111, // index[52] SERIAL_LINK_CHANNEL_ALLOC_TX_CH_EN
    4'b 0001, // index[53] SERIAL_LINK_CHANNEL_ALLOC_TX_CTRL
    4'b 0111, // index[54] SERIAL_LINK_CHANNEL_ALLOC_RX_CFG
    4'b 0001, // index[55] SERIAL_LINK_CHANNEL_ALLOC_RX_CTRL
    4'b 0111  // index[56] SERIAL_LINK_CHANNEL_ALLOC_RX_CH_EN
  };

endpackage

