# Copyright 2022 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Author: Tim Fischer <fischeti@iis.ee.ethz.ch>

name: lint

on: [push, pull_request]

jobs:

  ###############
  # Check Clean #
  ###############
  check-clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
        run: pip install -r requirements.txt
      - name: Install bender
        uses: pulp-platform/pulp-actions/bender-install@v2
      - name: Check clean make targets
        run: |
          make -B update-regs
          make clean
          git status && test -z "$(git status --porcelain)"

  ###############
  # Check Stale #
  ###############
  check-stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
        run: pip install -r requirements.txt
      - name: Install bender
        uses: pulp-platform/pulp-actions/bender-install@v2
      - name: Check clean makefile
        run: |
          make -B update-regs
          git status && test -z "$(git status --porcelain)"

  #####################
  # Bender up-to-date #
  #####################
  bender-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: Check Bender up-to-date
        uses: pulp-platform/pulp-actions/bender-up-to-date@v2

  ################
  # Verible Lint #
  ################
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: chipsalliance/verible-linter-action@main
      with:
        paths: |
          ./src
        exclude_paths: |
          ./src/regs
        extra_args: "--waiver_files util/verible.waiver"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_error: true
        reviewdog_reporter: github-check

  #################
  # Check License #
  #################
  check-licence:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
      run: pip install -r requirements.txt
    - name: Check license
      run: util/check-license
