# Copyright 2022 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Author: Tim Fischer <fischeti@iis.ee.ethz.ch>

name: lint

on: [push, pull_request]

jobs:

  ###############
  # Check Clean #
  ###############
  check-clean:
    runs-on: ubuntu-latest
    env:
      PEAKRDL: uv run peakrdl
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install bender
        uses: pulp-platform/pulp-actions/bender-install@v2.4.4
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Check clean targets
        run: |
          just gen-regs
          just clean
          git status && test -z "$(git status --porcelain)"

  ###############
  # Check Stale #
  ###############
  check-stale:
    runs-on: ubuntu-latest
    env:
      PEAKRDL: uv run peakrdl
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install bender
        uses: pulp-platform/pulp-actions/bender-install@v2.4.4
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Check stale targets
        run: |
          just gen-regs
          git status && test -z "$(git status --porcelain)"

  #####################
  # Bender up-to-date #
  #####################
  bender-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: Check Bender up-to-date
        uses: pulp-platform/pulp-actions/bender-up-to-date@v2.4.4

  ################
  # Verible Lint #
  ################
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: chipsalliance/verible-linter-action@main
      with:
        paths: |
          ./src
        exclude_paths: |
          ./src/regs
        extra_args: "--waiver_files util/verible.waiver"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_error: true
        reviewdog_reporter: github-check

  #########
  # REUSE #
  #########
  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: fsfe/reuse-action@v6
